version: '3'

services:
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        restart: always
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes: 
            - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto/data:/mosquitto/data
        networks:
            - default

    influxdb:
        container_name: influxdb
        image: influxdb
        restart: always
        ports:
            - "8086:8086"
        volumes:
            - ./influxdb2/data:/var/lib/influxdb2
            - ./influxdb2/backup:/var/lib/backup
        networks:
            - default

    telegraf:
        container_name: telegraf
        image: telegraf
        restart: always
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        environment:
          - INFLUXDB_V2_URL=${INFLUXDB_V2_URL}
          - INFLUXDB_V2_ORG=${INFLUXDB_V2_ORG}
          - INFLUXDB_V2_TOKEN=${INFLUXDB_V2_TOKEN}
          - INFLUXDB_V2_BUCKET_ENERGY=${INFLUXDB_V2_BUCKET_ENERGY}
          - MQTT_URL=${MQTT_URL}
          - MQTT_USER=${MQTT_USER}
          - MQTT_PASS=${MQTT_PASS}
          - MQTT_CLID=${MQTT_CLID}
          - MQTT_SUB_TOPIC=${MQTT_SUB_TOPIC}
        depends_on:
            - influxdb
            - mosquitto
        networks:
            - default

    grafana:
        container_name: grafana
        image: grafana/grafana
        restart: always
        ports:
          - "3000:3000"
        volumes:
          - ./grafana/data:/var/lib/grafana
        depends_on:
            - influxdb
        user: "1000"

    weather:
        container_name: weather
        build: ./weather_scraper
        command: /bin/bash -c "while true ; do /usr/local/bin/python /app/scrape_dtgweather.py ; sleep 300 ; done"
        environment:
          - INFLUXDB_V2_URL=${INFLUXDB_V2_URL}
          - INFLUXDB_V2_ORG=${INFLUXDB_V2_ORG}
          - INFLUXDB_V2_TOKEN=${INFLUXDB_V2_TOKEN}
          - INFLUXDB_V2_BUCKET_WEATHER=${INFLUXDB_V2_BUCKET_WEATHER}
        depends_on:
          - influxdb

networks:
    default:
